### ISSUE TITLE
Datum wordt over twee regels weergegeven

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/GeoDropIn#69]
In de lijst met ge-uploade bestanden wordt de datum nu over twee regels weergegeven. Wens is om de datum niet af te breken en op dus één regel weer te geven.

**Comment by KevinvdBosch** [comment]
Probleem doet zich voornamelijk voor in Chrome en Internet Explorer

**Comment by HermanAssink** [comment]
Opgelost
