### ISSUE TITLE
Ligging_gezoneerde_industrieterreinen_2019 is verwijderd in GeoDropIn, maar blijkbaar niet uit Oracle.

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/GeoDropIn#70]
Vermoedelijke oorzaak: naam is te lang voor Oracle. Dus controleren op de lengte van de naam.

**Comment by KevinvdBosch** [comment]
Bij het uploaden worden er diverse inserts in Oracle gedaan in de volgorde:
1. Rij toevoegen aan GDB_ITEMS_VW met de metadata
2. Tabel maken voor de dataset
3. Rij toevoegen aan USER_SDO_GEOM_METADATA

Door een verkeerd geometrie type gaat dit mis bij stap 2. Er is dus al wel metadata ingevoerd. Bij het verwijderen wordt vervolgens de volgende volgorde gehanteerd:
1. Verwijderen tabel met de dataset
2. Verwijderen rij uit USER_SDO_GEOM_METADATA
3. Verwijderen rij uit GDB_ITEMS_VW

Aan gezien het inserten mis is gegaan en hij geen tabel heeft gemaakt gaat het bij stap 1 al mis waardoor het programma stopt na de exceptie die optreed.

Als oplossing iedere stap afzonderlijk uit proberen te voeren en iets aan de foutafhandeling doen mocht het mis gaan bij eerdere stappen om toch door te kunnen en proberen zichzelf te herstellen

**Comment by HermanAssink** [comment]
Opgelost
